spring.application.name=Uber
# Database URL, Username, and Password
spring.datasource.url=jdbc:mysql://localhost:3306/uberservice
spring.datasource.username=root
spring.datasource.password=root

# Optional: Hibernate properties
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true